-- ====================================================================
-- 게시글 4개 생성 및 결제 내역 테이블 생성 SQL
-- ====================================================================

-- ====================
-- 1. 결제 내역 테이블 생성
-- ====================
CREATE TABLE payments (
    payment_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    reservation_id NUMBER REFERENCES reservations(reservation_id) ON DELETE CASCADE,
    member_num NUMBER REFERENCES users(member_num) ON DELETE CASCADE,
    amount NUMBER(12,2) NOT NULL,
    payment_method VARCHAR2(50) NOT NULL CHECK (payment_method IN ('CREDIT_CARD', 'DEBIT_CARD', 'BANK_TRANSFER', 'CASH')),
    payment_status VARCHAR2(20) DEFAULT 'COMPLETED' CHECK (payment_status IN ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED')),
    transaction_id VARCHAR2(100) UNIQUE,
    payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 결제 내역 인덱스 생성
CREATE INDEX idx_payments_reservation ON payments(reservation_id);
CREATE INDEX idx_payments_member ON payments(member_num);
CREATE INDEX idx_payments_date ON payments(payment_date);
CREATE INDEX idx_payments_status ON payments(payment_status);

-- ====================
-- 2. img 폴더 이미지를 사용한 게시글 4개 생성
-- ====================

-- 게시글 1: 시그니엘 호텔 (HOTEL 타입)
INSERT INTO posts (member_num, post_type, title, content, address, city, country, phone, file_name, view_count) 
VALUES (2, 'HOTEL', '서울 시그니엘 호텔', 
'서울 중심가에 위치한 최고급 럭셔리 호텔입니다. 세계적인 서비스와 최첨단 시설을 제공하며, 도시의 아름다운 전경을 감상할 수 있습니다. 
모든 객실은 최고급 아메니티와 편안한 침구를 갖추고 있으며, 24시간 룸서비스를 제공합니다.', 
'서울특별시 중구 을지로 30', '서울', 'KR', '02-1234-5678', 
'시그니엘 호텔.png', 1250);

-- 시그니엘 호텔의 객실 타입들
INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count, file_name) 
VALUES (2, 'ROOM_TYPE', (SELECT post_id FROM posts WHERE title = '서울 시그니엘 호텔' AND post_type = 'HOTEL'), 
'디럭스 룸', '32평의 넓은 공간과 도시 전경을 감상할 수 있는 최고급 객실입니다.', 350000, 25, 
'시그니엘 호텔.png');

INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count, file_name) 
VALUES (2, 'ROOM_TYPE', (SELECT post_id FROM posts WHERE title = '서울 시그니엘 호텔' AND post_type = 'HOTEL'), 
'스위트 룸', '50평의 프리미엄 스위트로 별도의 거실과 침실을 갖추고 있습니다.', 650000, 10, 
'시그니엘 호텔.png');

INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count, file_name) 
VALUES (2, 'ROOM_TYPE', (SELECT post_id FROM posts WHERE title = '서울 시그니엘 호텔' AND post_type = 'HOTEL'), 
'프레지덴셜 스위트', '100평의 최고급 스위트로 독립적인 체크인과 전용 버틀러 서비스를 제공합니다.', 1200000, 3, 
'시그니엘 호텔.png');

-- 게시글 2: 그랜드하얏트 호텔 (HOTEL 타입)
INSERT INTO posts (member_num, post_type, title, content, address, city, country, phone, file_name, view_count) 
VALUES (3, 'HOTEL', '서울 그랜드하얏트 호텔', 
'한국의 전통과 현대적 럭셔리가 조화를 이룬 최고급 호텔입니다. 
한강을 바라보는 전략적 위치에 자리잡고 있으며, 세계적인 서비스와 한국의 전통 문화를 체험할 수 있는 특별한 공간을 제공합니다.', 
'서울특별시 용산구 소월로 322', '서울', 'KR', '02-797-1234', 
'그랜드하얏트.png', 980);

-- 그랜드하얏트 호텔의 객실 타입들
INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count, file_name) 
VALUES (3, 'ROOM_TYPE', (SELECT post_id FROM posts WHERE title = '서울 그랜드하얏트 호텔' AND post_type = 'HOTEL'), 
'그랜드 킹 룸', '한강 전망을 감상할 수 있는 최고급 킹 사이즈 침대 객실입니다.', 280000, 30, 
'그랜드하얏트.png');

INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count, file_name) 
VALUES (3, 'ROOM_TYPE', (SELECT post_id FROM posts WHERE title = '서울 그랜드하얏트 호텔' AND post_type = 'HOTEL'), 
'그랜드 트윈 룸', '두 개의 더블 침대가 있는 넓은 객실로 가족 여행에 최적화되어 있습니다.', 320000, 20, 
'그랜드하얏트.png');

INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count, file_name) 
VALUES (3, 'ROOM_TYPE', (SELECT post_id FROM posts WHERE title = '서울 그랜드하얏트 호텔' AND post_type = 'HOTEL'), 
'그랜드 스위트', '별도의 거실과 침실을 갖춘 프리미엄 스위트입니다.', 580000, 8, 
'그랜드하얏트.png');

-- 게시글 3: 웨스틴 조선 호텔 (HOTEL 타입)
INSERT INTO posts (member_num, post_type, title, content, address, city, country, phone, file_name, view_count) 
VALUES (4, 'HOTEL', '서울 웨스틴 조선 호텔', 
'1934년 설립된 한국 최초의 럭셔리 호텔로, 전통과 현대가 조화를 이룬 최고급 호텔입니다. 
명동 중심가에 위치하여 쇼핑과 관광에 편리하며, 세계적인 서비스와 한국의 전통 문화를 체험할 수 있습니다.', 
'서울특별시 중구 소공로 87', '서울', 'KR', '02-771-0500', 
'웨스틴 조선.png', 1120);

-- 웨스틴 조선 호텔의 객실 타입들
INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count, file_name) 
VALUES (4, 'ROOM_TYPE', (SELECT post_id FROM posts WHERE title = '서울 웨스틴 조선 호텔' AND post_type = 'HOTEL'), 
'디럭스 룸', '전통과 현대가 조화를 이룬 아름다운 인테리어의 최고급 객실입니다.', 320000, 35, 
'웨스틴 조선.png');

INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count, file_name) 
VALUES (4, 'ROOM_TYPE', (SELECT post_id FROM posts WHERE title = '서울 웨스틴 조선 호텔' AND post_type = 'HOTEL'), 
'그랜드 디럭스 룸', '더욱 넓은 공간과 프리미엄 서비스를 제공하는 최고급 객실입니다.', 420000, 20, 
'웨스틴 조선.png');

INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count, file_name) 
VALUES (4, 'ROOM_TYPE', (SELECT post_id FROM posts WHERE title = '서울 웨스틴 조선 호텔' AND post_type = 'HOTEL'), 
'로얄 스위트', '한국의 전통 미학이 담긴 최고급 스위트로 독립적인 체크인 서비스를 제공합니다.', 850000, 5, 
'웨스틴 조선.png');

-- 게시글 4: 신라 호텔 (HOTEL 타입)
INSERT INTO posts (member_num, post_type, title, content, address, city, country, phone, file_name, view_count) 
VALUES (5, 'HOTEL', '서울 신라 호텔', 
'한국의 대표적인 럭셔리 호텔로, 23만평의 아름다운 정원과 함께하는 최고급 호텔입니다. 
전통과 현대가 조화를 이룬 독특한 분위기와 세계적인 서비스를 제공하며, 도시의 번잡함을 벗어난 평화로운 휴식을 경험할 수 있습니다.', 
'서울특별시 중구 동빙고로 249', '서울', 'KR', '02-2233-3131', 
'신라.png', 890);

-- 신라 호텔의 객실 타입들
INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count, file_name) 
VALUES (5, 'ROOM_TYPE', (SELECT post_id FROM posts WHERE title = '서울 신라 호텔' AND post_type = 'HOTEL'), 
'디럭스 룸', '아름다운 정원을 바라보는 최고급 객실로 편안한 휴식을 제공합니다.', 380000, 40, 
'신라.png');

INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count, file_name) 
VALUES (5, 'ROOM_TYPE', (SELECT post_id FROM posts WHERE title = '서울 신라 호텔' AND post_type = 'HOTEL'), 
'그랜드 디럭스 룸', '더욱 넓은 공간과 프리미엄 서비스를 제공하는 최고급 객실입니다.', 480000, 25, 
'신라.png');

INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count, file_name) 
VALUES (5, 'ROOM_TYPE', (SELECT post_id FROM posts WHERE title = '서울 신라 호텔' AND post_type = 'HOTEL'), 
'로얄 스위트', '한국의 전통 미학이 담긴 최고급 스위트로 독립적인 체크인과 전용 버틀러 서비스를 제공합니다.', 950000, 8, 
'신라.png');

-- ====================
-- 3. 결제 내역 데이터 생성 (최근 3개월)
-- ====================

-- 시그니엘 호텔 예약 및 결제 내역
INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (6, (SELECT post_id FROM posts WHERE title = '서울 시그니엘 호텔' AND post_type = 'HOTEL'), 
(SELECT post_id FROM posts WHERE title = '디럭스 룸' AND parent_id = (SELECT post_id FROM posts WHERE title = '서울 시그니엘 호텔' AND post_type = 'HOTEL')), 
'1501', DATE '2024-01-15', DATE '2024-01-17', 2, 0, 700000, TIMESTAMP '2024-01-10 14:30:00', 'CHECKED_OUT');

INSERT INTO payments (reservation_id, member_num, amount, payment_method, payment_status, transaction_id, payment_date) 
VALUES ((SELECT reservation_id FROM reservations WHERE member_num = 6 AND hotel_post_id = (SELECT post_id FROM posts WHERE title = '서울 시그니엘 호텔' AND post_type = 'HOTEL')), 
6, 700000, 'CREDIT_CARD', 'COMPLETED', 'TXN_SIGNIEL_001', TIMESTAMP '2024-01-10 14:30:00');

-- 그랜드하얏트 호텔 예약 및 결제 내역
INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (7, (SELECT post_id FROM posts WHERE title = '서울 그랜드하얏트 호텔' AND post_type = 'HOTEL'), 
(SELECT post_id FROM posts WHERE title = '그랜드 킹 룸' AND parent_id = (SELECT post_id FROM posts WHERE title = '서울 그랜드하얏트 호텔' AND post_type = 'HOTEL')), 
'2203', DATE '2024-02-20', DATE '2024-02-22', 2, 1, 840000, TIMESTAMP '2024-02-15 10:20:00', 'CHECKED_OUT');

INSERT INTO payments (reservation_id, member_num, amount, payment_method, payment_status, transaction_id, payment_date) 
VALUES ((SELECT reservation_id FROM reservations WHERE member_num = 7 AND hotel_post_id = (SELECT post_id FROM posts WHERE title = '서울 그랜드하얏트 호텔' AND post_type = 'HOTEL')), 
7, 840000, 'DEBIT_CARD', 'COMPLETED', 'TXN_GRAND_001', TIMESTAMP '2024-02-15 10:20:00');

-- 웨스틴 조선 호텔 예약 및 결제 내역
INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (8, (SELECT post_id FROM posts WHERE title = '서울 웨스틴 조선 호텔' AND post_type = 'HOTEL'), 
(SELECT post_id FROM posts WHERE title = '디럭스 룸' AND parent_id = (SELECT post_id FROM posts WHERE title = '서울 웨스틴 조선 호텔' AND post_type = 'HOTEL')), 
'1805', DATE '2024-03-10', DATE '2024-03-12', 3, 0, 960000, TIMESTAMP '2024-03-05 16:45:00', 'CONFIRMED');

INSERT INTO payments (reservation_id, member_num, amount, payment_method, payment_status, transaction_id, payment_date) 
VALUES ((SELECT reservation_id FROM reservations WHERE member_num = 8 AND hotel_post_id = (SELECT post_id FROM posts WHERE title = '서울 웨스틴 조선 호텔' AND post_type = 'HOTEL')), 
8, 960000, 'BANK_TRANSFER', 'COMPLETED', 'TXN_WESTIN_001', TIMESTAMP '2024-03-05 16:45:00');

-- 신라 호텔 예약 및 결제 내역
INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (9, (SELECT post_id FROM posts WHERE title = '서울 신라 호텔' AND post_type = 'HOTEL'), 
(SELECT post_id FROM posts WHERE title = '디럭스 룸' AND parent_id = (SELECT post_id FROM posts WHERE title = '서울 신라 호텔' AND post_type = 'HOTEL')), 
'2507', DATE '2024-03-25', DATE '2024-03-27', 2, 0, 760000, TIMESTAMP '2024-03-20 09:15:00', 'CONFIRMED');

INSERT INTO payments (reservation_id, member_num, amount, payment_method, payment_status, transaction_id, payment_date) 
VALUES ((SELECT reservation_id FROM reservations WHERE member_num = 9 AND hotel_post_id = (SELECT post_id FROM posts WHERE title = '서울 신라 호텔' AND post_type = 'HOTEL')), 
9, 760000, 'CREDIT_CARD', 'COMPLETED', 'TXN_SHILLA_001', TIMESTAMP '2024-03-20 09:15:00');

-- ====================
-- 4. 추가 결제 내역 (다양한 결제 방법과 상태)
-- ====================

-- 실패한 결제 내역
INSERT INTO payments (reservation_id, member_num, amount, payment_method, payment_status, transaction_id, payment_date) 
VALUES ((SELECT reservation_id FROM reservations WHERE member_num = 6 AND hotel_post_id = (SELECT post_id FROM posts WHERE title = '서울 시그니엘 호텔' AND post_type = 'HOTEL')), 
6, 700000, 'CREDIT_CARD', 'FAILED', 'TXN_SIGNIEL_FAIL_001', TIMESTAMP '2024-01-10 14:25:00');

-- 환불된 결제 내역
INSERT INTO payments (reservation_id, member_num, amount, payment_method, payment_status, transaction_id, payment_date) 
VALUES ((SELECT reservation_id FROM reservations WHERE member_num = 7 AND hotel_post_id = (SELECT post_id FROM posts WHERE title = '서울 그랜드하얏트 호텔' AND post_type = 'HOTEL')), 
7, 840000, 'DEBIT_CARD', 'REFUNDED', 'TXN_GRAND_REFUND_001', TIMESTAMP '2024-02-15 10:20:00');

-- 대기 중인 결제 내역
INSERT INTO payments (reservation_id, member_num, amount, payment_method, payment_status, transaction_id, payment_date) 
VALUES ((SELECT reservation_id FROM reservations WHERE member_num = 8 AND hotel_post_id = (SELECT post_id FROM posts WHERE title = '서울 웨스틴 조선 호텔' AND post_type = 'HOTEL')), 
8, 960000, 'BANK_TRANSFER', 'PENDING', 'TXN_WESTIN_PENDING_001', TIMESTAMP '2024-03-05 16:40:00');

-- ====================
-- 5. 확인 쿼리
-- ====================

-- 생성된 호텔 게시글 확인
SELECT post_id, title, city, address, view_count, file_name FROM posts WHERE post_type = 'HOTEL' ORDER BY post_id DESC;

-- 생성된 객실 타입 확인
SELECT p1.title as hotel_name, p2.title as room_type, p2.price, p2.room_count, p2.file_name 
FROM posts p1 
JOIN posts p2 ON p1.post_id = p2.parent_id 
WHERE p1.post_type = 'HOTEL' AND p2.post_type = 'ROOM_TYPE' 
ORDER BY p1.post_id, p2.price;

-- 결제 내역 확인
SELECT p.payment_id, p.amount, p.payment_method, p.payment_status, p.transaction_id, p.payment_date,
       u.name as customer_name, h.title as hotel_name
FROM payments p
JOIN reservations r ON p.reservation_id = r.reservation_id
JOIN users u ON p.member_num = u.member_num
JOIN posts h ON r.hotel_post_id = h.post_id
ORDER BY p.payment_date DESC;

-- 월별 결제 통계
SELECT TO_CHAR(payment_date, 'YYYY-MM') as month,
       COUNT(*) as total_payments,
       SUM(amount) as total_amount,
       AVG(amount) as avg_amount
FROM payments 
WHERE payment_status = 'COMPLETED'
GROUP BY TO_CHAR(payment_date, 'YYYY-MM')
ORDER BY month DESC;

COMMIT;
