-- ====================================================================
-- 오라클 호텔 예약 시스템 완전한 데이터베이스 생성 스크립트 (업데이트 버전)
-- ====================================================================

-- ====================================
-- 1. 사용자 생성 및 권한 부여 (SYS 또는 SYSTEM 계정으로 실행)
-- ====================================
CREATE USER hotel_admin IDENTIFIED BY root;
GRANT CONNECT, RESOURCE TO hotel_admin;
GRANT UNLIMITED TABLESPACE TO hotel_admin;
GRANT CREATE VIEW TO hotel_admin;
GRANT CREATE SYNONYM TO hotel_admin;

SELECT * from posts WHERE member_num = 3;



-- ====================================
-- 2. 사용자 전환 후 테이블 생성 (hotel_admin으로 접속)
-- ====================================
-- CONNECT hotel_admin/password123;

-- ====================
-- 1. 사용자 테이블 (IDENTITY 방식)
-- ====================
CREATE TABLE users (
    member_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 자동 증가 기본키
    username VARCHAR2(50) UNIQUE NOT NULL, -- 사용자명 (로그인용, 중복 불가)
    password VARCHAR2(255) NOT NULL, -- 비밀번호 (암호화 저장)
    email VARCHAR2(100) UNIQUE NOT NULL, -- 이메일 주소 (중복 불가)
    name VARCHAR2(100) NOT NULL, -- 실명
    phone VARCHAR2(20), -- 전화번호
    birth_date DATE, -- 생년월일
    gender CHAR(1) CHECK (gender IN ('M', 'F')), -- 성별 (M:남성, F:여성)
    user_type VARCHAR2(20) DEFAULT 'USER' CHECK (user_type IN ('USER', 'HOTEL_MANAGER', 'ADMIN')), -- 사용자 타입
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 가입 일시
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- 정보 수정 일시
);

SELECT * FROM posts;


-- ====================
-- 2. 통합 게시글 테이블 (IDENTITY 방식)
-- ====================
CREATE TABLE posts (
    post_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 자동 증가 기본키
    parent_id NUMBER, -- 부모 게시글 ID (계층 구조용)
    member_num NUMBER REFERENCES users(member_num), -- 작성자 회원번호
    post_type VARCHAR2(30) NOT NULL CHECK (post_type IN ('HOTEL', 'ROOM_TYPE', 'FACILITY', 'IMAGE', 'NOTICE', 'EVENT', 'REVIEW')), -- 게시글 타입
    title VARCHAR2(200) NOT NULL, -- 제목
    content CLOB, -- 내용
    address VARCHAR2(300), -- 주소 (호텔용)
    city VARCHAR2(50), -- 도시 (호텔용)
    country VARCHAR2(50), -- 국가 (호텔용)
    phone VARCHAR2(20), -- 전화번호 (호텔용)
    price NUMBER(10,2), -- 가격 (객실타입용, 1박 기준)
    room_count NUMBER(3) DEFAULT 0, -- 객실 개수 (객실타입용)
    image_url VARCHAR2(500), -- 이미지 URL (이미지용)
    file_name VARCHAR2(200), -- 파일명 (이미지용)
    display_order NUMBER(5) DEFAULT 0, -- 표시 순서
    view_count NUMBER(10) DEFAULT 0, -- 조회수
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 작성 일시
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- 수정 일시
);
SELECT * from posts;

SELECT * FROM posts WHERE post_type = 'FACILITY';

-- 1. 하위 posts(객실, 시설 등) 삭제
DELETE FROM posts WHERE parent_id = 2;

-- 2. 예약 데이터 삭제
DELETE FROM reservations WHERE hotel_post_id = 2;

-- 3. 댓글/리뷰 삭제
DELETE FROM comments WHERE post_id = 2;

-- 4. 호텔(부모) 삭제
DELETE FROM posts WHERE post_id = 2;
-- ====================
-- 3. 예약 테이블 (IDENTITY 방식) - 상태 간소화
-- ====================
CREATE TABLE reservations (
    reservation_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 자동 증가 기본키
    member_num NUMBER REFERENCES users(member_num) ON DELETE CASCADE, -- 예약자 회원번호
    hotel_post_id NUMBER REFERENCES posts(post_id), -- 호텔 게시글 ID
    room_post_id NUMBER REFERENCES posts(post_id), -- 객실타입 게시글 ID
    room_number VARCHAR2(10), -- 실제 배정된 객실 번호
    check_in_date DATE NOT NULL, -- 체크인 날짜
    check_out_date DATE NOT NULL, -- 체크아웃 날짜
    adults NUMBER(2) DEFAULT 1, -- 성인 인원수
    children NUMBER(2) DEFAULT 0, -- 아동 인원수
    total_nights NUMBER(5), -- 총 숙박 일수 (자동 계산)
    total_amount NUMBER(12,2) NOT NULL, -- 총 결제 금액
    booking_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 예약 일시 (= 결제 일시)
    status VARCHAR2(20) DEFAULT 'CONFIRMED' CHECK (status IN ('CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT')), -- 예약 상태 (간소화)
    special_requests CLOB, -- 특별 요청사항
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 생성 일시
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 수정 일시
    CONSTRAINT chk_dates CHECK (check_out_date > check_in_date) -- 체크아웃이 체크인보다 나중이어야 함
);

-- 숙박 일수 자동 계산 트리거
CREATE OR REPLACE TRIGGER trg_reservations_nights
    BEFORE INSERT OR UPDATE ON reservations
    FOR EACH ROW
BEGIN
    :NEW.total_nights := :NEW.check_out_date - :NEW.check_in_date; -- 숙박 일수 자동 계산
END;
/

-- ====================
-- 4. 댓글/리뷰 테이블 (IDENTITY 방식)
-- ====================
CREATE TABLE comments (
    comment_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 자동 증가 기본키
    post_id NUMBER REFERENCES posts(post_id) ON DELETE CASCADE, -- 게시글 ID
    member_num NUMBER REFERENCES users(member_num) ON DELETE CASCADE, -- 작성자 회원번호
    reservation_id NUMBER REFERENCES reservations(reservation_id), -- 예약 ID (리뷰인 경우)
    parent_comment_id NUMBER, -- 부모 댓글 ID (대댓글용)
    content CLOB NOT NULL, -- 댓글 내용
    rating NUMBER(2,1) CHECK (rating BETWEEN 1.0 AND 5.0), -- 평점 (1.0~5.0, 리뷰인 경우)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 작성 일시
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- 수정 일시
);

-- ====================
-- 5. 예약 상태 자동 업데이트 시스템
-- ====================

-- 예약 상태 자동 업데이트 프로시저
CREATE OR REPLACE PROCEDURE update_reservation_status AS
BEGIN
    -- 체크인 날짜가 되면 CONFIRMED → CHECKED_IN
    UPDATE reservations 
    SET status = 'CHECKED_IN', 
        updated_at = CURRENT_TIMESTAMP
    WHERE status = 'CONFIRMED' 
    AND TRUNC(check_in_date) <= TRUNC(SYSDATE);
    
    -- 체크아웃 날짜가 되면 CHECKED_IN → CHECKED_OUT
    UPDATE reservations 
    SET status = 'CHECKED_OUT', 
        updated_at = CURRENT_TIMESTAMP
    WHERE status = 'CHECKED_IN' 
    AND TRUNC(check_out_date) <= TRUNC(SYSDATE);
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('예약 상태 업데이트 완료: ' || TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'));
END;
/

-- 매일 자동 실행 스케줄러 생성
BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
        job_name        => 'AUTO_UPDATE_RESERVATION_STATUS',
        job_type        => 'PLSQL_BLOCK',
        job_action      => 'BEGIN update_reservation_status; END;',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=DAILY; BYHOUR=1; BYMINUTE=0; BYSECOND=0',
        enabled         => TRUE,
        comments        => '예약 상태 자동 업데이트 (매일 오전 1시)'
    );
END;
/

-- ====================
-- 인덱스 생성
-- ====================
-- 사용자 테이블 인덱스
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_type ON users(user_type);

-- 게시글 테이블 인덱스
CREATE INDEX idx_posts_type ON posts(post_type);
CREATE INDEX idx_posts_parent ON posts(parent_id);
CREATE INDEX idx_posts_city ON posts(city);
CREATE INDEX idx_posts_member ON posts(member_num);

-- 예약 테이블 인덱스
CREATE INDEX idx_reservations_dates ON reservations(check_in_date, check_out_date);
CREATE INDEX idx_reservations_member ON reservations(member_num);
CREATE INDEX idx_reservations_hotel ON reservations(hotel_post_id);
CREATE INDEX idx_reservations_status ON reservations(status);
CREATE INDEX idx_reservations_booking_date ON reservations(booking_date);

-- 댓글 테이블 인덱스
CREATE INDEX idx_comments_post ON comments(post_id);
CREATE INDEX idx_comments_member ON comments(member_num);
CREATE INDEX idx_comments_reservation ON comments(reservation_id);

-- ====================================================================
-- 각 파트별 핵심 PreparedStatement 쿼리문
-- ====================================================================

-- ==================== 파트 1 (김진영 - 로그인/회원가입/이메일 인증) ====================
-- 회원가입
INSERT INTO users (username, password, email, name, phone, birth_date, gender, user_type) VALUES (?, ?, ?, ?, ?, ?, ?, ?);

-- 로그인
SELECT member_num, username, email, name, user_type FROM users WHERE (email = ? OR username = ?) AND password = ?;

-- 사용자 정보 조회
SELECT member_num, username, email, name, phone, birth_date, gender, user_type, created_at FROM users WHERE member_num = ?;

-- ==================== 파트 2 (박석우 - 게시글 CRUD/페이징/사진 첨부) ====================
-- 게시글 생성 (모든 컬럼 포함)
INSERT INTO posts (parent_id, member_num, post_type, title, content, address, city, country, phone, price, room_count, image_url, file_name, display_order, view_count) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);

-- 호텔 목록 조회 (페이징)
SELECT * FROM (SELECT ROWNUM rn, a.* FROM (SELECT post_id, title, city, address, view_count, created_at FROM posts WHERE post_type = 'HOTEL' ORDER BY created_at DESC) a WHERE ROWNUM <= ?) WHERE rn > ?;

-- 특정 호텔의 객실타입 조회
SELECT post_id, title, content, price, room_count FROM posts WHERE parent_id = ? AND post_type = 'ROOM_TYPE' ORDER BY price;

-- 게시글 수정
UPDATE posts SET title = ?, content = ?, updated_at = CURRENT_TIMESTAMP WHERE post_id = ? AND member_num = ?;

-- ==================== 파트 3 (최수빈 - 예약시스템/결제) ====================
-- 예약 생성 (결제 완료 시 바로 확정)
INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, special_requests) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);

-- 사용자별 예약 목록 조회
SELECT r.reservation_id, h.title as hotel_name, rt.title as room_type, r.room_number, r.check_in_date, r.check_out_date, r.total_amount, r.status, r.booking_date FROM reservations r JOIN posts h ON r.hotel_post_id = h.post_id JOIN posts rt ON r.room_post_id = rt.post_id WHERE r.member_num = ? ORDER BY r.booking_date DESC;

-- 객실 타입 정보 조회 (예약 가능 여부는 자바에서 처리)
SELECT rt.post_id, rt.title, rt.price, rt.room_count FROM posts rt WHERE rt.post_type = 'ROOM_TYPE' AND rt.parent_id = ? ORDER BY rt.price;

-- 특정 날짜 범위의 예약 조회 (자바에서 예약 가능 여부 확인용)
SELECT room_post_id, COUNT(*) as booked_count FROM reservations WHERE hotel_post_id = ? AND status IN ('CONFIRMED', 'CHECKED_IN') AND ((check_in_date <= ? AND check_out_date > ?) OR (check_in_date < ? AND check_out_date >= ?)) GROUP BY room_post_id;

-- 예약 상태 변경 (수동)
UPDATE reservations SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE reservation_id = ? AND member_num = ?;

-- ==================== 파트 4 (김효진 - 호텔매니저/통계 대시보드/매출 분석) ====================
-- 호텔 매니저의 예약 현황 조회
SELECT r.reservation_id, h.title as hotel_name, u.name as guest_name, rt.title as room_type, r.check_in_date, r.check_out_date, r.total_amount, r.status, r.booking_date FROM reservations r JOIN users u ON r.member_num = u.member_num JOIN posts h ON r.hotel_post_id = h.post_id JOIN posts rt ON r.room_post_id = rt.post_id WHERE h.member_num = ? ORDER BY r.booking_date DESC;

-- 호텔 매니저의 일별 매출 조회 (최근 30일)
SELECT TRUNC(r.booking_date) as booking_day, COUNT(*) as daily_reservations, COUNT(CASE WHEN r.status IN ('CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT') THEN 1 END) as confirmed_reservations, SUM(CASE WHEN r.status IN ('CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT') THEN r.total_amount ELSE 0 END) as daily_revenue FROM reservations r JOIN posts h ON r.hotel_post_id = h.post_id WHERE h.member_num = ? AND h.post_type = 'HOTEL' AND r.booking_date >= TRUNC(SYSDATE) - 30 GROUP BY TRUNC(r.booking_date) ORDER BY booking_day DESC;

-- 오늘 매출 조회
SELECT COUNT(*) as today_reservations, SUM(CASE WHEN status IN ('CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT') THEN total_amount ELSE 0 END) as today_revenue FROM reservations r JOIN posts h ON r.hotel_post_id = h.post_id WHERE h.member_num = ? AND h.post_type = 'HOTEL' AND TRUNC(r.booking_date) = TRUNC(SYSDATE);

-- 월별 매출 분석
SELECT TO_CHAR(booking_date, 'YYYY-MM') as month, COUNT(*) as total_reservations, SUM(CASE WHEN status IN ('CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT') THEN total_amount ELSE 0 END) as confirmed_revenue FROM reservations WHERE hotel_post_id IN (SELECT post_id FROM posts WHERE member_num = ? AND post_type = 'HOTEL') GROUP BY TO_CHAR(booking_date, 'YYYY-MM') ORDER BY month DESC;

-- 객실타입별 매출 분석
SELECT rt.title as room_type, rt.price, COUNT(r.reservation_id) as total_bookings, SUM(CASE WHEN r.status IN ('CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT') THEN r.total_amount ELSE 0 END) as total_revenue FROM posts rt LEFT JOIN reservations r ON rt.post_id = r.room_post_id WHERE rt.post_type = 'ROOM_TYPE' AND rt.parent_id IN (SELECT post_id FROM posts WHERE member_num = ? AND post_type = 'HOTEL') GROUP BY rt.post_id, rt.title, rt.price ORDER BY total_revenue DESC NULLS LAST;

-- 월평균 매출 조회 (manager1 기준)
SELECT ROUND(AVG(monthly_revenue), 0) as average_monthly_revenue FROM (SELECT TO_CHAR(r.booking_date, 'YYYY-MM') as month_year, SUM(CASE WHEN r.status IN ('CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT') THEN r.total_amount ELSE 0 END) as monthly_revenue FROM reservations r JOIN posts h ON r.hotel_post_id = h.post_id JOIN users u ON h.member_num = u.member_num WHERE u.username = 'manager1' AND h.post_type = 'HOTEL' GROUP BY TO_CHAR(r.booking_date, 'YYYY-MM'));

-- ==================== 공통 유틸리티 쿼리 ====================
-- 리뷰 작성
INSERT INTO comments (post_id, member_num, reservation_id, content, rating) VALUES (?, ?, ?, ?, ?);

-- 호텔 검색 (도시별)
SELECT post_id, title, city, address, view_count FROM posts WHERE post_type = 'HOTEL' AND (city LIKE '%' || ? || '%' OR title LIKE '%' || ? || '%') ORDER BY view_count DESC;

-- 조회수 증가
UPDATE posts SET view_count = view_count + 1, updated_at = CURRENT_TIMESTAMP WHERE post_id = ?;

-- ====================================================================
-- 파트 4 (김효진) 개발용 임의 데이터 삽입
-- ====================================================================

-- ==================== 샘플 사용자 데이터 ====================
-- 관리자 계정
INSERT INTO users (username, password, email, name, user_type) 
VALUES ('admin', 'admin123', 'admin@hotel.com', '시스템관리자', 'ADMIN');

-- 호텔 매니저들
INSERT INTO users (username, password, email, name, phone, user_type) 
VALUES ('manager1', 'manager123', 'manager1@grandhotel.com', '김그랜드', '02-1234-5678', 'HOTEL_MANAGER');

INSERT INTO users (username, password, email, name, phone, user_type) 
VALUES ('manager2', 'manager123', 'manager2@oceanhotel.com', '이오션', '051-9876-5432', 'HOTEL_MANAGER');

INSERT INTO users (username, password, email, name, phone, user_type) 
VALUES ('manager3', 'manager123', 'manager3@mountainhotel.com', '박마운틴', '033-1111-2222', 'HOTEL_MANAGER');

-- 일반 사용자들
INSERT INTO users (username, password, email, name, phone, gender) 
VALUES ('user1', 'user123', 'user1@gmail.com', '홍길동', '010-1234-5678', 'M');

INSERT INTO users (username, password, email, name, phone, gender) 
VALUES ('user2', 'user123', 'user2@gmail.com', '김영희', '010-9876-5432', 'F');

INSERT INTO users (username, password, email, name, phone, gender) 
VALUES ('user3', 'user123', 'user3@gmail.com', '박철수', '010-5555-6666', 'M');

INSERT INTO users (username, password, email, name, phone, gender) 
VALUES ('user4', 'user123', 'user4@gmail.com', '이미영', '010-7777-8888', 'F');

INSERT INTO users (username, password, email, name, phone, gender) 
VALUES ('user5', 'user123', 'user5@gmail.com', '정민수', '010-9999-0000', 'M');

-- ==================== 호텔 게시글 데이터 ====================
-- 그랜드 호텔 (매니저1)
INSERT INTO posts (member_num, post_type, title, content, address, city, country, phone) 
VALUES (2, 'HOTEL', '서울 그랜드 호텔', '서울 중심가에 위치한 럭셔리 호텔입니다. 최고급 서비스와 편의시설을 제공합니다.', '서울특별시 중구 명동길 123', '서울', 'KR', '02-1234-5678');

-- 부산 오션뷰 호텔 (매니저2)
INSERT INTO posts (member_num, post_type, title, content, address, city, country, phone) 
VALUES (3, 'HOTEL', '부산 오션뷰 호텔', '해운대 바닷가에 위치한 오션뷰 전문 호텔입니다. 모든 객실에서 바다를 감상할 수 있습니다.', '부산광역시 해운대구 해운대해변로 264', '부산', 'KR', '051-9876-5432');

-- 강원도 마운틴 리조트 (매니저3)
INSERT INTO posts (member_num, post_type, title, content, address, city, country, phone) 
VALUES (4, 'HOTEL', '강원도 마운틴 리조트', '설악산 자락에 위치한 힐링 리조트입니다. 자연과 함께하는 휴식을 제공합니다.', '강원도 속초시 설악산로 456', '속초', 'KR', '033-1111-2222');

-- ==================== 객실타입 데이터 ====================
-- 그랜드 호텔 객실타입들
INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count) 
VALUES (2, 'ROOM_TYPE', 1, '스탠다드룸', '기본형 객실로 편안한 휴식을 제공합니다.', 120000, 15);

INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count) 
VALUES (2, 'ROOM_TYPE', 1, '프리미엄룸', '고급스러운 인테리어와 도시 전망을 자랑하는 객실입니다.', 180000, 10);

INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count) 
VALUES (2, 'ROOM_TYPE', 1, '디럭스룸', '최고급 객실로 넓은 공간과 럭셔리한 시설을 제공합니다.', 250000, 8);

INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count) 
VALUES (2, 'ROOM_TYPE', 1, '스위트룸', '별실과 거실이 분리된 최상급 스위트룸입니다.', 400000, 5);

-- 오션뷰 호텔 객실타입들
INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count) 
VALUES (3, 'ROOM_TYPE', 2, '오션뷰 스탠다드', '바다가 보이는 기본 객실입니다.', 150000, 12);

INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count) 
VALUES (3, 'ROOM_TYPE', 2, '오션뷰 디럭스', '넓은 발코니와 멋진 바다 전망을 자랑합니다.', 220000, 8);

INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count) 
VALUES (3, 'ROOM_TYPE', 2, '오션뷰 스위트', '최고급 바다 전망 스위트룸입니다.', 350000, 4);

-- 마운틴 리조트 객실타입들
INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count) 
VALUES (4, 'ROOM_TYPE', 3, '마운틴뷰 스탠다드', '산이 보이는 기본 객실입니다.', 100000, 20);

INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count) 
VALUES (4, 'ROOM_TYPE', 3, '마운틴뷰 디럭스', '넓은 테라스와 산 전망을 자랑합니다.', 160000, 12);

INSERT INTO posts (member_num, post_type, parent_id, title, content, price, room_count) 
VALUES (4, 'ROOM_TYPE', 3, '프리미엄 빌라', '독립된 빌라 타입 객실입니다.', 280000, 6);

-- ==================== 예약 데이터 (최근 3개월) ====================
-- 그랜드 호텔 예약들 (1월)
INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (5, 1, 4, '201', DATE '2024-01-15', DATE '2024-01-17', 2, 0, 240000, TIMESTAMP '2024-01-10 14:30:00', 'CHECKED_OUT');

INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (6, 1, 5, '301', DATE '2024-01-20', DATE '2024-01-22', 2, 1, 360000, TIMESTAMP '2024-01-15 10:20:00', 'CHECKED_OUT');

INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (7, 1, 6, '401', DATE '2024-01-25', DATE '2024-01-27', 3, 0, 500000, TIMESTAMP '2024-01-20 16:45:00', 'CHECKED_OUT');

-- 그랜드 호텔 예약들 (2월)
INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (8, 1, 4, '202', DATE '2024-02-10', DATE '2024-02-12', 2, 0, 240000, TIMESTAMP '2024-02-05 09:15:00', 'CHECKED_OUT');

INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (9, 1, 5, '302', DATE '2024-02-14', DATE '2024-02-16', 2, 0, 360000, TIMESTAMP '2024-02-10 13:30:00', 'CHECKED_OUT');

INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (5, 1, 7, '501', DATE '2024-02-20', DATE '2024-02-23', 4, 2, 1200000, TIMESTAMP '2024-02-15 11:20:00', 'CHECKED_OUT');

-- 그랜드 호텔 예약들 (3월)
INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (6, 1, 4, '203', DATE '2024-03-05', DATE '2024-03-07', 2, 0, 240000, TIMESTAMP '2024-03-01 15:45:00', 'CHECKED_OUT');

INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (7, 1, 5, '303', DATE '2024-03-12', DATE '2024-03-14', 2, 1, 360000, TIMESTAMP '2024-03-08 12:10:00', 'CHECKED_OUT');

INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (8, 1, 6, '402', DATE '2024-03-18', DATE '2024-03-20', 2, 0, 500000, TIMESTAMP '2024-03-15 14:20:00', 'CHECKED_OUT');

-- 오션뷰 호텔 예약들 (1월)
INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (9, 2, 8, '101', DATE '2024-01-18', DATE '2024-01-20', 2, 0, 300000, TIMESTAMP '2024-01-12 10:30:00', 'CHECKED_OUT');

INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (5, 2, 9, '201', DATE '2024-01-25', DATE '2024-01-27', 2, 1, 440000, TIMESTAMP '2024-01-20 16:15:00', 'CHECKED_OUT');

-- 오션뷰 호텔 예약들 (2월)
INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (6, 2, 8, '102', DATE '2024-02-08', DATE '2024-02-10', 2, 0, 300000, TIMESTAMP '2024-02-03 14:25:00', 'CHECKED_OUT');

INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (7, 2, 10, '301', DATE '2024-02-15', DATE '2024-02-17', 3, 1, 700000, TIMESTAMP '2024-02-10 09:40:00', 'CHECKED_OUT');

-- 오션뷰 호텔 예약들 (3월)
INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (8, 2, 9, '202', DATE '2024-03-10', DATE '2024-03-12', 2, 0, 440000, TIMESTAMP '2024-03-05 11:50:00', 'CHECKED_OUT');

INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (9, 2, 8, '103', DATE '2024-03-20', DATE '2024-03-22', 2, 0, 300000, TIMESTAMP '2024-03-15 13:30:00', 'CHECKED_OUT');

-- 마운틴 리조트 예약들 (1월)
INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (5, 3, 11, '101', DATE '2024-01-22', DATE '2024-01-24', 2, 0, 200000, TIMESTAMP '2024-01-17 12:20:00', 'CHECKED_OUT');

INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (6, 3, 12, '201', DATE '2024-01-28', DATE '2024-01-30', 2, 1, 320000, TIMESTAMP '2024-01-23 15:10:00', 'CHECKED_OUT');

-- 마운틴 리조트 예약들 (2월)
INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (7, 3, 13, '301', DATE '2024-02-12', DATE '2024-02-15', 4, 2, 840000, TIMESTAMP '2024-02-07 10:30:00', 'CHECKED_OUT');

INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (8, 3, 11, '102', DATE '2024-02-25', DATE '2024-02-27', 2, 0, 200000, TIMESTAMP '2024-02-20 14:45:00', 'CHECKED_OUT');

-- 마운틴 리조트 예약들 (3월)
INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (9, 3, 12, '202', DATE '2024-03-08', DATE '2024-03-10', 2, 0, 320000, TIMESTAMP '2024-03-03 16:20:00', 'CHECKED_OUT');

INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (5, 3, 13, '302', DATE '2024-03-22', DATE '2024-03-25', 3, 1, 840000, TIMESTAMP '2024-03-18 11:15:00', 'CHECKED_OUT');

-- 현재 활성 예약들 (자동 상태 변경 테스트용)
INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (6, 1, 4, '204', SYSDATE + 1, SYSDATE + 3, 2, 0, 240000, CURRENT_TIMESTAMP, 'CONFIRMED');

INSERT INTO reservations (member_num, hotel_post_id, room_post_id, room_number, check_in_date, check_out_date, adults, children, total_amount, booking_date, status) 
VALUES (7, 2, 8, '104', SYSDATE, SYSDATE + 2, 2, 0, 300000, CURRENT_TIMESTAMP, 'CONFIRMED');

-- 커밋
COMMIT;

-- ==================== 개발용 테스트 쿼리 ====================
-- 매니저별 매출 요약 확인
SELECT '=== 호텔 매니저별 매출 현황 ===' as status FROM dual;

SELECT 
    u.name as manager_name,
    h.title as hotel_name,
    COUNT(r.reservation_id) as total_reservations,
    SUM(r.total_amount) as total_revenue,
    ROUND(AVG(r.total_amount), 0) as avg_revenue
FROM users u
JOIN posts h ON u.member_num = h.member_num
LEFT JOIN reservations r ON h.post_id = r.hotel_post_id
WHERE u.user_type = 'HOTEL_MANAGER' AND h.post_type = 'HOTEL'
GROUP BY u.member_num, u.name, h.post_id, h.title
ORDER BY total_revenue DESC;

-- 월별 매출 현황 확인 (실시간 계산)
SELECT '=== 월별 매출 현황 (실시간) ===' as status FROM dual;

SELECT 
    TO_CHAR(r.booking_date, 'YYYY-MM') as month,
    h.title as hotel_name,
    COUNT(r.reservation_id) as reservations_count,
    SUM(CASE WHEN r.status IN ('CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT') 
        THEN r.total_amount ELSE 0 END) as monthly_revenue
FROM reservations r
JOIN posts h ON r.hotel_post_id = h.post_id
WHERE h.post_type = 'HOTEL'
GROUP BY TO_CHAR(r.booking_date, 'YYYY-MM'), h.title
ORDER BY month, monthly_revenue DESC;

-- 자동 상태 업데이트 테스트
SELECT '=== 자동 상태 업데이트 시스템 활성화됨 ===' as status FROM dual;

-- 스케줄러 상태 확인
SELECT 
    job_name, 
    enabled, 
    state, 
    next_run_date, 
    last_start_date 
FROM user_scheduler_jobs 
WHERE job_name = 'AUTO_UPDATE_RESERVATION_STATUS';

SELECT '파트 4 개발용 업데이트된 데이터 생성 완료!' as message FROM dual; 

-- ====================================================================
-- 추가 유틸리티: 스케줄러 관리 명령어들
-- ====================================================================

-- 스케줄러 수동 실행: EXEC update_reservation_status;
-- 스케줄러 중지: EXEC DBMS_SCHEDULER.DISABLE('AUTO_UPDATE_RESERVATION_STATUS');
-- 스케줄러 재시작: EXEC DBMS_SCHEDULER.ENABLE('AUTO_UPDATE_RESERVATION_STATUS');
-- 스케줄러 삭제: EXEC DBMS_SCHEDULER.DROP_JOB('AUTO_UPDATE_RESERVATION_STATUS');